import { timingSafeEqual } from "crypto";
import { NextRequest,NextResponse } from "next/server";
import { getSubscriptionState,type SubscriptionState } from "@/lib/subscription";
import { createAdminSupabaseClient,createBotAuthSupabaseClient } from "@/lib/supabase/admin";
import { fetchDriveFile } from "@/lib/google-drive";
import { SITE_NAME } from "@/lib/site";
import {
  TELEGRAM_MAX_OUTGOING_BYTES,answerTelegramCallback,paymentKeyboard,paymentMessage,receiptUsername,
  sendTelegramDocument,sendTelegramMessage,telegramBackToMenuKeyboard,telegramMainKeyboard,
  telegramWebhookSecret,telegramWelcomeKeyboard
} from "@/lib/telegram";

type TgUser={id:number;username?:string;first_name?:string};
type TgMessage={chat:{id:number;type?:string};from?:TgUser;text?:string;document?:unknown;photo?:unknown[]};
type TgCallback={id:string;from:TgUser;data?:string;message?:{chat:{id:number}}};
type TgUpdate={message?:TgMessage;callback_query?:TgCallback};
type BotMode="idle"|"download"|"request_title"|"request_author"|"request_language";
type BotContext={title?:string;author?:string};
type LinkedState={userId:string;isAdmin:boolean;approved:boolean;mode:BotMode;context:BotContext;subscription:SubscriptionState|null};
type Access={userId:string;isAdmin:boolean;mode:BotMode;context:BotContext;activeUntil:string|null};
type BookFormat="pdf"|"epub";

function validSecret(value:string|null){if(!value)return false;const expected=telegramWebhookSecret();const a=Buffer.from(value);const b=Buffer.from(expected);return a.length===b.length&&timingSafeEqual(a,b);}
function escapeHtml(value:string){return String(value||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");}
function normalized(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();}
function formatDate(value?:string|null){if(!value)return "—";return new Intl.DateTimeFormat("pt-BR",{timeZone:"America/Sao_Paulo",day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(value));}
function isPdf(book:any){return book?.mime_type==="application/pdf"||String(book?.file_name||"").toLowerCase().endsWith(".pdf");}
function isEpub(book:any){return book?.mime_type==="application/epub+zip"||String(book?.file_name||"").toLowerCase().endsWith(".epub");}

async function getLinkedState(user:TgUser,chatId:number):Promise<LinkedState|null>{
  const admin=createAdminSupabaseClient();const {data:account}=await admin.from("telegram_accounts").select("user_id,bot_mode,bot_context").eq("telegram_user_id",user.id).maybeSingle();if(!account)return null;
  await admin.from("telegram_accounts").update({chat_id:chatId,username:user.username||null,first_name:user.first_name||null,updated_at:new Date().toISOString()}).eq("telegram_user_id",user.id);
  const {data:profile}=await admin.from("profiles").select("approved,role").eq("id",account.user_id).maybeSingle();const isAdmin=profile?.role==="admin";const subscription=isAdmin?null:await getSubscriptionState(account.user_id);
  return {userId:account.user_id,isAdmin,approved:Boolean(profile?.approved),mode:(account.bot_mode||"idle") as BotMode,context:(account.bot_context||{}) as BotContext,subscription};
}

async function requireAccess(user:TgUser,chatId:number):Promise<Access|null>{
  const state=await getLinkedState(user,chatId);if(!state){await showWelcome(chatId);return null;}
  if(state.isAdmin)return {userId:state.userId,isAdmin:true,mode:state.mode,context:state.context,activeUntil:null};
  if(!state.approved||!state.subscription?.isActive){await sendTelegramMessage(chatId,paymentMessage(),paymentKeyboard());return null;}
  return {userId:state.userId,isAdmin:false,mode:state.mode,context:state.context,activeUntil:state.subscription.activeUntil};
}

async function setState(telegramUserId:number,mode:BotMode,context:BotContext={}){await createAdminSupabaseClient().from("telegram_accounts").update({bot_mode:mode,bot_context:context,updated_at:new Date().toISOString()}).eq("telegram_user_id",telegramUserId);}
async function showWelcome(chatId:number){await sendTelegramMessage(chatId,`📚 <b>Bem-vindo à ${SITE_NAME}</b>\n\n${paymentMessage().replace(/^📚[^\n]+\n\n/,"")}`,telegramWelcomeKeyboard());}

async function beginLogin(user:TgUser,chatId:number){
  const admin=createAdminSupabaseClient();const now=Date.now();await admin.from("telegram_login_sessions").upsert({telegram_user_id:user.id,chat_id:chatId,username:user.username||null,first_name:user.first_name||null,stage:"email",email:null,attempts:0,locked_until:null,expires_at:new Date(now+15*60_000).toISOString(),updated_at:new Date().toISOString()},{onConflict:"telegram_user_id"});
  await sendTelegramMessage(chatId,"🔐 <b>Entrar na sua conta</b>\n\nEnvie agora o <b>e-mail de login</b> fornecido pelo administrador.\n\nPor segurança, faça isso somente em uma conversa privada com o bot.",{inline_keyboard:[[{text:"↩️ CANCELAR",callback_data:"cancel_login"}]]});
}

async function handleLoginText(user:TgUser,chatId:number,raw:string){
  const admin=createAdminSupabaseClient();const {data:session}=await admin.from("telegram_login_sessions").select("*").eq("telegram_user_id",user.id).maybeSingle();if(!session)return false;
  if(new Date(session.expires_at).getTime()<=Date.now()){await admin.from("telegram_login_sessions").delete().eq("telegram_user_id",user.id);await sendTelegramMessage(chatId,"⌛ O tempo para entrar expirou. Toque novamente em <b>Já tenho acesso</b>.",telegramWelcomeKeyboard());return true;}
  if(session.locked_until&&new Date(session.locked_until).getTime()>Date.now()){await sendTelegramMessage(chatId,"🔒 Muitas tentativas incorretas. Aguarde 15 minutos e tente novamente.");return true;}
  if(session.stage==="email"){
    const email=raw.trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email)){await sendTelegramMessage(chatId,"Esse e-mail não parece válido. Digite novamente.");return true;}
    await admin.from("telegram_login_sessions").update({email,stage:"password",updated_at:new Date().toISOString()}).eq("telegram_user_id",user.id);await sendTelegramMessage(chatId,"Agora envie a <b>senha</b> fornecida pelo administrador.\n\n🔐 A senha é usada somente nesta tentativa e não é armazenada pelo bot.");return true;
  }
  const email=String(session.email||"");const auth=createBotAuthSupabaseClient();const {data,error}=await auth.auth.signInWithPassword({email,password:raw});
  if(error||!data.user){const attempts=Number(session.attempts||0)+1;const lockedUntil=attempts>=5?new Date(Date.now()+15*60_000).toISOString():null;await admin.from("telegram_login_sessions").update({attempts,locked_until:lockedUntil,updated_at:new Date().toISOString()}).eq("telegram_user_id",user.id);await sendTelegramMessage(chatId,lockedUntil?"🔒 E-mail ou senha incorretos. O acesso foi pausado por 15 minutos.":`❌ E-mail ou senha incorretos. Tente novamente (${5-attempts} tentativas restantes).`);return true;}
  await auth.auth.signOut();
  const [{data:profile},subscription,{data:existing}]=await Promise.all([admin.from("profiles").select("approved,role").eq("id",data.user.id).maybeSingle(),getSubscriptionState(data.user.id),admin.from("telegram_accounts").select("telegram_user_id").eq("user_id",data.user.id).maybeSingle()]);
  const isAdmin=profile?.role==="admin";if(!profile||(profile.role!=="admin"&&!profile.approved)||(!isAdmin&&!subscription.isActive)){await admin.from("telegram_login_sessions").delete().eq("telegram_user_id",user.id);await sendTelegramMessage(chatId,"⏳ Seus dados estão corretos, mas a assinatura ainda não foi liberada. Envie o comprovante ao atendimento.",telegramWelcomeKeyboard());return true;}
  if(existing&&Number(existing.telegram_user_id)!==user.id){await admin.from("telegram_login_sessions").delete().eq("telegram_user_id",user.id);await sendTelegramMessage(chatId,"🔒 Esta conta já está conectada em outro Telegram. Para usar aqui, primeiro toque em <b>Sair / Trocar conta</b> no chat onde ela está ativa.",telegramWelcomeKeyboard());return true;}
  const {error:linkError}=await admin.from("telegram_accounts").upsert({user_id:data.user.id,telegram_user_id:user.id,chat_id:chatId,username:user.username||null,first_name:user.first_name||null,bot_mode:"idle",bot_context:{},updated_at:new Date().toISOString()},{onConflict:"user_id"});if(linkError){await sendTelegramMessage(chatId,"Não foi possível vincular esta conta. Ela pode estar ativa em outro Telegram.",telegramWelcomeKeyboard());return true;}
  await admin.from("telegram_login_sessions").delete().eq("telegram_user_id",user.id);await sendTelegramMessage(chatId,"✅ <b>Login realizado!</b>\n\nSua conta foi vinculada a este Telegram. Enquanto ela estiver ativa aqui, não poderá ser usada em outro chat do bot.");await showMenu(user,chatId);return true;
}

async function logout(user:TgUser,chatId:number){const admin=createAdminSupabaseClient();await Promise.all([admin.from("telegram_accounts").delete().eq("telegram_user_id",user.id),admin.from("telegram_login_sessions").delete().eq("telegram_user_id",user.id)]);await sendTelegramMessage(chatId,"🚪 <b>Você saiu da conta.</b>\n\nO acesso foi liberado para entrar em outro Telegram. Se quiser usar outra conta aqui, toque em <b>Já tenho acesso</b>.",telegramWelcomeKeyboard());}

async function showMenu(user:TgUser,chatId:number){const access=await requireAccess(user,chatId);if(!access)return;await setState(user.id,"idle",{});const name=user.first_name?`, <b>${escapeHtml(user.first_name)}</b>`:"";const status=access.isAdmin?"🛡 Acesso administrativo":`✅ Assinatura ativa até ${formatDate(access.activeUntil)}`;await sendTelegramMessage(chatId,`📚 <b>${SITE_NAME}</b>\n\nOlá${name}!\n${status}\n\nVocê pode baixar um livro disponível ou enviar um pedido para o acervo.`,telegramMainKeyboard());}
async function showSubscription(user:TgUser,chatId:number){const state=await getLinkedState(user,chatId);if(!state){await showWelcome(chatId);return;}if(state.isAdmin){await sendTelegramMessage(chatId,"🛡 Sua conta de administrador possui acesso permanente.",telegramMainKeyboard());return;}if(state.approved&&state.subscription?.isActive){await sendTelegramMessage(chatId,`💳 <b>Assinatura ativa</b>\n\n📅 Início: ${formatDate(state.subscription.activatedAt)}\n⏳ Vencimento: ${formatDate(state.subscription.activeUntil)}`,telegramMainKeyboard());return;}await sendTelegramMessage(chatId,paymentMessage(),paymentKeyboard());}

async function promptDownload(user:TgUser,chatId:number){if(!await requireAccess(user,chatId))return;await setState(user.id,"download",{});await sendTelegramMessage(chatId,"🔎 <b>Buscar livro</b>\n\nDigite o título ou o nome do autor.",telegramBackToMenuKeyboard());}
async function searchBooks(user:TgUser,chatId:number,raw:string){if(!await requireAccess(user,chatId))return;const term=raw.replace(/[%_]/g," ").replace(/\s+/g," ").trim();if(term.length<2){await sendTelegramMessage(chatId,"Digite pelo menos 2 caracteres.");return;}const pattern=`%${term}%`;const {data}=await createAdminSupabaseClient().from("books").select("id,title,author,file_name,mime_type,reading_pdf_drive_file_id,kindle_drive_file_id").eq("published",true).eq("allow_download",true).or(`title.ilike.${pattern},author.ilike.${pattern}`).limit(10);const results=data||[];if(!results.length){await sendTelegramMessage(chatId,`🔎 Nenhum livro encontrado para “${escapeHtml(term)}”.\n\nVocê também pode pedir esse título pelo menu.`,telegramMainKeyboard());await setState(user.id,"idle",{});return;}const exact=results.find(book=>normalized(book.title)===normalized(term));if(exact||results.length===1){await showFormats(user,chatId,(exact||results[0]).id);return;}await sendTelegramMessage(chatId,"Escolha o livro:",{inline_keyboard:[...results.map(book=>[{text:`📚 ${book.title}`.slice(0,60),callback_data:`book:${book.id}`}]),[{text:"↩️ Voltar",callback_data:"show_menu"}]]});}

async function loadBook(id:string){const {data}=await createAdminSupabaseClient().from("books").select("*").eq("id",id).eq("published",true).eq("allow_download",true).maybeSingle();return data;}
async function showFormats(user:TgUser,chatId:number,id:string){if(!await requireAccess(user,chatId))return;const book=await loadBook(id);if(!book){await sendTelegramMessage(chatId,"Livro indisponível.",telegramMainKeyboard());return;}const pdf=isPdf(book)||Boolean(book.reading_pdf_drive_file_id);const epub=isEpub(book)||Boolean(book.kindle_drive_file_id);const rows:Array<Array<Record<string,string>>> = [];if(pdf)rows.push([{text:"📄 BAIXAR PDF",callback_data:`format:${id}:pdf`}]);if(epub)rows.push([{text:"📱 BAIXAR EPUB",callback_data:`format:${id}:epub`}]);rows.push([{text:"↩️ Voltar",callback_data:"show_menu"}]);await setState(user.id,"idle",{});await sendTelegramMessage(chatId,`📖 <b>${escapeHtml(book.title)}</b>\n👤 ${escapeHtml(book.author)}\n\nEscolha o formato:`,{inline_keyboard:rows});}

async function sendBook(user:TgUser,chatId:number,id:string,format:BookFormat){const access=await requireAccess(user,chatId);if(!access)return;const book=await loadBook(id);if(!book)return;let fileId:string|undefined;let fileName:string|undefined;let mime:string;if(format==="pdf"){if(isPdf(book)){fileId=book.drive_file_id;fileName=book.file_name;}else{fileId=book.reading_pdf_drive_file_id;fileName=book.reading_pdf_file_name;}mime="application/pdf";}else{if(isEpub(book)){fileId=book.drive_file_id;fileName=book.file_name;}else{fileId=book.kindle_drive_file_id;fileName=book.kindle_file_name;}mime="application/epub+zip";}if(!fileId||!fileName){await sendTelegramMessage(chatId,"Esse formato não está disponível.",telegramMainKeyboard());return;}await sendTelegramMessage(chatId,"⏳ Preparando o arquivo...");const response=await fetchDriveFile(fileId);const declared=Number(response.headers.get("content-length")||0);if(declared>TELEGRAM_MAX_OUTGOING_BYTES){await sendTelegramMessage(chatId,"O arquivo é grande demais para envio pelo Telegram. Baixe pelo site.",telegramMainKeyboard());return;}const bytes=new Uint8Array(await response.arrayBuffer());if(bytes.byteLength>TELEGRAM_MAX_OUTGOING_BYTES){await sendTelegramMessage(chatId,"O arquivo é grande demais para envio pelo Telegram. Baixe pelo site.",telegramMainKeyboard());return;}await sendTelegramDocument(chatId,fileName,mime,bytes,`📚 <b>${escapeHtml(book.title)}</b>\n${format.toUpperCase()}`);await createAdminSupabaseClient().from("telegram_download_history").insert({user_id:access.userId,source:"catalog",book_id:id,title_snapshot:book.title,format,requested_at:new Date().toISOString()});await sendTelegramMessage(chatId,"✅ Livro enviado.",telegramMainKeyboard());}

async function showHistory(user:TgUser,chatId:number){const access=await requireAccess(user,chatId);if(!access)return;const {data}=await createAdminSupabaseClient().from("telegram_download_history").select("id,book_id,title_snapshot,format").eq("user_id",access.userId).eq("source","catalog").order("requested_at",{ascending:false}).limit(20);const unique=(data||[]).filter((row,index,rows)=>rows.findIndex(item=>item.book_id===row.book_id&&item.format===row.format)===index).slice(0,10);if(!unique.length){await sendTelegramMessage(chatId,"Seu histórico ainda está vazio.",telegramMainKeyboard());return;}await sendTelegramMessage(chatId,"🕘 <b>Histórico de downloads</b>",{inline_keyboard:[...unique.map(row=>[{text:`${row.format==="pdf"?"📄":"📱"} ${row.title_snapshot}`.slice(0,60),callback_data:`format:${row.book_id}:${row.format}`}]),[{text:"↩️ Voltar",callback_data:"show_menu"}]]});}

async function beginRequest(user:TgUser,chatId:number){if(!await requireAccess(user,chatId))return;await setState(user.id,"request_title",{});await sendTelegramMessage(chatId,"📝 <b>Pedir um livro</b>\n\nQual é o <b>título</b> do livro?",telegramBackToMenuKeyboard());}
async function handleRequest(user:TgUser,chatId:number,access:Access,raw:string){const value=raw.trim();if(value.length<2){await sendTelegramMessage(chatId,"Digite pelo menos 2 caracteres.");return;}if(access.mode==="request_title"){await setState(user.id,"request_author",{title:value.slice(0,220)});await sendTelegramMessage(chatId,"Quem é o <b>autor</b> do livro?");return;}if(access.mode==="request_author"){await setState(user.id,"request_language",{...access.context,author:value.slice(0,220)});await sendTelegramMessage(chatId,"Em qual <b>idioma</b> você deseja o livro?\nExemplo: Português, Inglês ou Espanhol.");return;}if(access.mode==="request_language"){const title=access.context.title;const author=access.context.author;if(!title||!author){await setState(user.id,"idle",{});return;}const admin=createAdminSupabaseClient();const {error}=await admin.from("book_requests").insert({user_id:access.userId,title,author,language:value.slice(0,80)});await setState(user.id,"idle",{});if(error){await sendTelegramMessage(chatId,"Não consegui registrar o pedido agora. Tente novamente.",telegramMainKeyboard());return;}await sendTelegramMessage(chatId,`✅ <b>Pedido enviado!</b>\n\n📚 ${escapeHtml(title)}\n👤 ${escapeHtml(author)}\n🌎 ${escapeHtml(value)}\n\nQuando o livro for publicado, você receberá uma notificação automática com o link.`,telegramMainKeyboard());}}

export async function POST(request:NextRequest){
  try{
    if(!validSecret(request.headers.get("x-telegram-bot-api-secret-token")))return NextResponse.json({ok:false},{status:401});const update=await request.json() as TgUpdate;
    if(update.callback_query){const query=update.callback_query;const chatId=query.message?.chat.id;if(!chatId){await answerTelegramCallback(query.id);return NextResponse.json({ok:true});}const data=query.data||"";await answerTelegramCallback(query.id);if(data==="action_login")await beginLogin(query.from,chatId);else if(data==="cancel_login"){await createAdminSupabaseClient().from("telegram_login_sessions").delete().eq("telegram_user_id",query.from.id);await showWelcome(chatId);}else if(data==="subscription_paid")await sendTelegramMessage(chatId,`✅ Envie o comprovante para <b>@${receiptUsername()}</b>. Depois da confirmação, você receberá seu e-mail e senha.`,telegramWelcomeKeyboard());else if(data==="action_logout")await logout(query.from,chatId);else if(data==="show_menu")await showMenu(query.from,chatId);else if(data==="show_subscription")await showSubscription(query.from,chatId);else if(data==="action_download")await promptDownload(query.from,chatId);else if(data==="action_request")await beginRequest(query.from,chatId);else if(data==="show_history")await showHistory(query.from,chatId);else if(data.startsWith("book:"))await showFormats(query.from,chatId,data.split(":")[1]);else if(data.startsWith("format:")){const [,id,format]=data.split(":");if(format==="pdf"||format==="epub")await sendBook(query.from,chatId,id,format);}return NextResponse.json({ok:true});}
    const message=update.message;const user=message?.from;const chatId=message?.chat.id;if(!message||!user||!chatId)return NextResponse.json({ok:true});if(message.chat.type&&message.chat.type!=="private"){await sendTelegramMessage(chatId,"Por segurança, use este bot somente em uma conversa privada.");return NextResponse.json({ok:true});}
    const raw=(message.text||"").trim();const lower=raw.toLowerCase();if(lower.startsWith("/sair")){await logout(user,chatId);return NextResponse.json({ok:true});}if(await handleLoginText(user,chatId,raw))return NextResponse.json({ok:true});if(lower.startsWith("/start")||lower.startsWith("/menu")){const linked=await getLinkedState(user,chatId);if(linked)await showMenu(user,chatId);else await showWelcome(chatId);return NextResponse.json({ok:true});}if(lower.startsWith("/baixar")){await promptDownload(user,chatId);return NextResponse.json({ok:true});}if(lower.startsWith("/pedir")){await beginRequest(user,chatId);return NextResponse.json({ok:true});}if(lower.startsWith("/historico")){await showHistory(user,chatId);return NextResponse.json({ok:true});}if(lower.startsWith("/assinatura")){await showSubscription(user,chatId);return NextResponse.json({ok:true});}
    const access=await requireAccess(user,chatId);if(!access)return NextResponse.json({ok:true});if(message.document||message.photo){await sendTelegramMessage(chatId,"Este bot não recebe arquivos. Use <b>Baixar livro</b> ou <b>Pedir livro</b>.",telegramMainKeyboard());return NextResponse.json({ok:true});}if(access.mode==="download"&&raw)await searchBooks(user,chatId,raw);else if(["request_title","request_author","request_language"].includes(access.mode)&&raw)await handleRequest(user,chatId,access,raw);else await showMenu(user,chatId);return NextResponse.json({ok:true});
  }catch(error){console.error("[telegram-webhook]",error instanceof Error?error.message:"unknown");return NextResponse.json({ok:true});}
}

export async function GET(){return NextResponse.json({ok:true,service:"estante-virtual-telegram"});}
