"use client";
import { useEffect,useMemo,useState } from "react";
import { driveFileName } from "@/lib/slugify";
import type { Book,BookMetadataResult,Category,Profile } from "@/lib/types";
type Props={initialBooks:Book[];initialCategories:Category[];initialProfiles:Profile[]};
export function AdminDashboard({initialBooks,initialCategories,initialProfiles}:Props){
 const [tab,setTab]=useState<"livros"|"categorias"|"usuarios"|"drive">("livros"),[books,setBooks]=useState(initialBooks),[categories,setCategories]=useState(initialCategories),[profiles,setProfiles]=useState(initialProfiles),[message,setMessage]=useState(""),[uploading,setUploading]=useState(false),[title,setTitle]=useState(""),[file,setFile]=useState<File|null>(null),[suggestions,setSuggestions]=useState<BookMetadataResult[]>([]),[searching,setSearching]=useState(false),[selected,setSelected]=useState<BookMetadataResult|null>(null),[drive,setDrive]=useState<{connected:boolean;accountEmail?:string|null}>({connected:false});
 const computedFileName=useMemo(()=>driveFileName(title,file?.name),[title,file?.name]);
 useEffect(()=>{ if(tab!=="drive")return; fetch("/api/drive/status").then(r=>r.json()).then(setDrive).catch(()=>{}); },[tab]);
 useEffect(()=>{ setSelected(null); if(title.trim().length<3){setSuggestions([]);return;} const c=new AbortController(); const t=setTimeout(async()=>{setSearching(true);try{const r=await fetch(`/api/book-metadata?title=${encodeURIComponent(title)}`,{signal:c.signal});const d=await r.json();if(r.ok)setSuggestions(d.results||[]);}catch{}setSearching(false);},550);return()=>{clearTimeout(t);c.abort();};},[title]);
 function choose(item:BookMetadataResult){setSelected(item);setTitle(item.title);setSuggestions([]);}
 async function addBook(formData:FormData){if(!file){setMessage("Selecione o arquivo do livro.");return;}setUploading(true);setMessage("");try{const sr=await fetch("/api/drive/upload-url",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,originalFileName:file.name,mimeType:file.type||"application/pdf",fileSize:file.size})});const s=await sr.json();if(!sr.ok){if(s.needsConnection)setTab("drive");throw new Error(s.error||"Falha ao preparar upload.");}const ur=await fetch(s.uploadUrl,{method:"PUT",headers:{"Content-Type":file.type||"application/pdf"},body:file});if(!ur.ok)throw new Error(`Upload do Drive falhou (${ur.status}).`);const df=await ur.json();const br=await fetch("/api/admin/books",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,author:String(formData.get("author")||selected?.author||""),description:String(formData.get("description")||selected?.description||""),year:String(formData.get("year")||selected?.year||""),pages:String(formData.get("pages")||selected?.pages||""),coverUrl:String(formData.get("cover_url")||selected?.coverUrl||""),categoryId:String(formData.get("category_id")||"")||null,driveFileId:df.id,fileName:s.fileName,mimeType:file.type||"application/pdf",published:formData.get("published")==="on",allowDownload:formData.get("allow_download")==="on"})});const saved=await br.json();if(!br.ok)throw new Error(saved.error||"Erro ao salvar livro.");setBooks(p=>[saved.book,...p]);setTitle("");setFile(null);setSelected(null);setMessage("Livro enviado e cadastrado com sucesso.");(document.getElementById("book-form") as HTMLFormElement|null)?.reset();}catch(e){setMessage(e instanceof Error?e.message:"Erro no upload.");}finally{setUploading(false);}}
 async function removeBook(id:string){if(!confirm("Remover este livro do catálogo?"))return;const r=await fetch(`/api/admin/books?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(r.ok)setBooks(p=>p.filter(b=>b.id!==id));}
 async function addCategory(fd:FormData){const r=await fetch("/api/admin/categories",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:String(fd.get("name")||"")})});const d=await r.json();if(r.ok)setCategories(p=>[...p,d.category].sort((a,b)=>a.name.localeCompare(b.name)));else setMessage(d.error||"Erro ao criar categoria.");}
 async function removeCategory(id:string){const r=await fetch(`/api/admin/categories?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(r.ok)setCategories(p=>p.filter(c=>c.id!==id));}
 async function updateUser(id:string,patch:{approved?:boolean;role?:string}){const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...patch})});if(r.ok)setProfiles(p=>p.map(x=>x.id===id?{...x,...patch}:x));}
 async function connectDrive(){const r=await fetch("/api/drive/auth-url");const d=await r.json();if(r.ok&&d.url)location.href=d.url;else setMessage(d.error||"Não foi possível conectar o Drive.");}
 return <><div className="tabs">{[["livros","Livros"],["categorias","Categorias"],["usuarios","Usuários"],["drive","Google Drive"]].map(([k,l])=><button key={k} className={`tab ${tab===k?"active":""}`} onClick={()=>setTab(k as any)}>{l}</button>)}</div>{message&&<div className={`notice ${message.includes("sucesso")?"success":""}`} style={{marginBottom:16}}>{message}</div>}
 {tab==="livros"&&<div className="admin-grid"><section className="card panel"><h2>Adicionar livro</h2><form id="book-form" className="stack" action={addBook}><label className="suggestion-box">Título<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: Crônicas de Fogo" required/>{searching&&<small className="muted">Buscando dados...</small>}{!!suggestions.length&&<div className="suggestions">{suggestions.map(i=><button type="button" className="suggestion" key={i.id} onClick={()=>choose(i)}>{i.coverUrl?<img src={i.coverUrl} alt=""/>:<span/>}<span><strong>{i.title}</strong><small>{i.author}{i.year?` • ${i.year}`:""}</small></span></button>)}</div>}</label><div className="file-preview">No Google Drive: <b>{computedFileName}</b></div><label>Arquivo<input type="file" accept=".pdf,.epub,application/pdf,application/epub+zip" onChange={e=>setFile(e.target.files?.[0]||null)} required/></label><label>Autor<input name="author" key={`a-${selected?.id||""}`} defaultValue={selected?.author||""}/></label><div className="row"><label style={{flex:1}}>Ano<input name="year" type="number" key={`y-${selected?.id||""}`} defaultValue={selected?.year||""}/></label><label style={{flex:1}}>Páginas<input name="pages" type="number" key={`p-${selected?.id||""}`} defaultValue={selected?.pages||""}/></label></div><label>Sinopse<textarea name="description" key={`d-${selected?.id||""}`} defaultValue={selected?.description||""}/></label><label>URL da capa<input name="cover_url" key={`c-${selected?.id||""}`} defaultValue={selected?.coverUrl||""}/></label><label>Categoria<select name="category_id" defaultValue=""><option value="">Sem categoria</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="row wrap"><label style={{display:"flex",alignItems:"center"}}><input name="published" type="checkbox" defaultChecked style={{width:"auto"}}/> Publicado</label><label style={{display:"flex",alignItems:"center"}}><input name="allow_download" type="checkbox" style={{width:"auto"}}/> Permitir download</label></div><button className="btn" disabled={uploading||!title||!file}>{uploading?"Enviando para o Drive...":"Adicionar livro"}</button></form></section><section className="card panel"><h2>Livros cadastrados</h2><div className="table-list">{books.map(b=><div className="table-row" key={b.id}><div><strong>{b.title}</strong><div className="meta">{b.author} • {b.file_name}</div></div><button className="btn danger" onClick={()=>removeBook(b.id)}>Excluir</button></div>)}</div></section></div>}
 {tab==="categorias"&&<section className="card panel"><h2>Categorias</h2><form className="row" action={addCategory}><input name="name" placeholder="Nova categoria" required/><button className="btn">Adicionar</button></form><div className="table-list">{categories.map(c=><div className="table-row" key={c.id}><strong>{c.name}</strong><button className="btn danger" onClick={()=>removeCategory(c.id)}>Excluir</button></div>)}</div></section>}
 {tab==="usuarios"&&<section className="card panel"><h2>Usuários</h2><div className="table-list">{profiles.map(p=><div className="table-row" key={p.id}><div><strong>{p.full_name||p.email||"Usuário"}</strong><div className="meta">{p.email} • {p.role} • {p.approved?"aprovado":"aguardando"}</div></div><div className="row wrap"><button className="btn" onClick={()=>updateUser(p.id,{approved:!p.approved})}>{p.approved?"Bloquear":"Aprovar"}</button><button className="btn ghost" onClick={()=>updateUser(p.id,{role:p.role==="admin"?"reader":"admin"})}>{p.role==="admin"?"Tornar leitor":"Tornar admin"}</button></div></div>)}</div></section>}
 {tab==="drive"&&<section className="card panel" style={{maxWidth:700}}><h2>Google Drive</h2><div className="row"><span className={`status-dot ${drive.connected?"on":""}`}/><strong>{drive.connected?"Conectado":"Não conectado"}</strong></div>{drive.accountEmail&&<p className="muted">Conta: {drive.accountEmail}</p>}<p className="muted">Os livros ficam no seu Drive pessoal, organizados em BIBLIOTECA VIRTUAL/A–Z.</p><button className="btn" onClick={connectDrive}>{drive.connected?"Reconectar Google Drive":"Conectar Google Drive"}</button></section>}</>;
}
