create table if not exists public.telegram_channels (
  id uuid primary key default gen_random_uuid(),
  chat_id bigint not null unique,
  title text,
  role text not null check (role in ('official','reserve')),
  active boolean not null default true,
  welcome_sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists telegram_channels_role_key
  on public.telegram_channels(role);

create table if not exists public.telegram_channel_publications (
  id bigint generated by default as identity primary key,
  book_id uuid not null references public.books(id) on delete cascade,
  channel_id uuid not null references public.telegram_channels(id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending','sent','partial','failed')),
  text_message_id bigint,
  epub_message_id bigint,
  pdf_message_id bigint,
  last_error text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(book_id, channel_id)
);

alter table public.telegram_channels enable row level security;
alter table public.telegram_channel_publications enable row level security;
revoke all on table public.telegram_channels from anon, authenticated;
revoke all on table public.telegram_channel_publications from anon, authenticated;
grant all on table public.telegram_channels to service_role;
grant all on table public.telegram_channel_publications to service_role;
