import { AppShell } from "@/components/AppShell";

const faqs=[
  {q:"Como enviar um livro ao meu Kindle?",a:"Abra Enviar ao Kindle, pesquise o livro, escolha um arquivo PDF ou EPUB e salve. Depois toque em Enviar ao Kindle. No celular, a Biblioteca Virtual abre o menu nativo de compartilhamento com o arquivo anexado; escolha o app Kindle para concluir."},
  {q:"Quais formatos são suportados?",a:"Para Enviar ao Kindle, a Biblioteca aceita PDF e EPUB de até 200 MB. Para leitura dentro do catálogo do site, usamos PDF, porque ele abre diretamente no leitor do navegador sem precisar baixar."},
  {q:"A Biblioteca converte PDF para EPUB?",a:"Não automaticamente. PDF já é aceito pelo Send to Kindle e converter PDF para EPUB pode quebrar fontes, imagens e paginação. Por isso enviamos o arquivo compatível original ao Kindle. EPUB continua aceito quando o usuário já possui um EPUB."},
  {q:"Consigo ler sem baixar?",a:"Sim. Livros em PDF publicados no catálogo abrem dentro do leitor da Biblioteca Virtual. O download só acontece quando houver permissão e o usuário tocar explicitamente em Baixar PDF."},
  {q:"Por que o Kindle não aparece no menu de compartilhamento?",a:"Confira se o app Kindle está instalado no celular. No iPhone ou Android, abra Mais/Outros no menu de compartilhamento e procure Kindle. Se o navegador não permitir compartilhar arquivos diretamente, a Biblioteca oferece o download do arquivo como alternativa."},
  {q:"Quem consegue ver o e-book que eu enviei?",a:"O e-book aparece primeiro na sua Minha Biblioteca e entra como Pendente para o administrador. O administrador pode marcar Privado, deixando-o apenas para você, ou aprovar um PDF para o catálogo geral."},
  {q:"O que significa Aprovado?",a:"Quando um PDF é aprovado, ele sai da fila Envios dos usuários, entra na aba Aprovados do painel e passa a aparecer no Acervo da Biblioteca. O administrador pode torná-lo privado novamente ou excluí-lo."},
  {q:"Onde ficam armazenados os arquivos?",a:"Os e-books e capas enviados ficam armazenados de forma privada no Google Drive conectado à Biblioteca Virtual, em uma pasta separada para cada usuário."},
  {q:"Por que autor, idioma e sinopse são pedidos?",a:"Esses dados organizam corretamente o catálogo. Ao escolher um resultado da pesquisa, a Biblioteca tenta preencher automaticamente título, autor, idioma, ano, páginas, categoria, sinopse e capa. Autor e sinopse são obrigatórios antes de salvar."},
  {q:"Meu upload falhou. O que devo verificar?",a:"Confirme se o arquivo é PDF ou EPUB, se possui até 200 MB e se sua conexão está estável. Não feche a página durante o envio."}
];

export default function HelpPage(){return <AppShell><main className="container help-page"><div className="page-head"><div><h1>Precisa de ajuda?</h1><p>Respostas rápidas sobre leitura, catálogo e envio de e-books ao Kindle.</p></div></div><section className="help-intro card panel"><div className="help-badge">?</div><div><h2>Central de ajuda</h2><p className="muted">Toque em uma pergunta para abrir a resposta.</p></div></section><section className="faq-list">{faqs.map((item,index)=><details className="card faq-item" key={item.q} open={index===0}><summary>{item.q}<span>+</span></summary><div className="faq-answer">{item.a}</div></details>)}</section></main></AppShell>;}
