import { AppShell } from "@/components/AppShell";

const faqs=[
  {q:"Como enviar um livro ao meu Kindle?",a:"Abra Enviar ao Kindle, pesquise o livro, selecione o PDF e escolha a capa. A Biblioteca salva o PDF para leitura e prepara uma versão EPUB com a capa incorporada. Depois toque em Enviar ao Kindle. No celular, será aberto o menu nativo de compartilhamento; escolha o app Kindle."},
  {q:"Qual formato eu devo enviar para a Biblioteca?",a:"Para novos envios, use PDF de até 200 MB. O PDF é a cópia oficial usada para leitura dentro do site. A Biblioteca cria uma segunda cópia em EPUB para o Kindle quando o arquivo possui texto suficiente para uma conversão de boa qualidade."},
  {q:"A Biblioteca converte PDF para EPUB?",a:"Sim. O PDF original não é alterado. Uma versão EPUB separada é criada somente para o Kindle, com título, autor, idioma e capa incorporados. Se o PDF for apenas uma digitalização por imagens e não tiver texto extraível suficiente, o sistema preserva o PDF e avisa que não consegue produzir um EPUB confiável."},
  {q:"Posso escolher outra capa para o Kindle?",a:"Sim. Se a Biblioteca possuir mais de uma capa para o mesmo título e autor, ao tocar em Enviar ao Kindle você poderá escolher qual capa deseja incorporar ao EPUB. Isso não altera o PDF nem a capa usada por outro usuário."},
  {q:"Consigo ler sem baixar?",a:"Sim. Livros em PDF publicados no catálogo abrem dentro do leitor da Biblioteca Virtual. Livros pessoais em PDF também podem ser abertos para leitura. O download só ocorre quando você escolhe uma ação de download."},
  {q:"Por que o Kindle não aparece no menu de compartilhamento?",a:"Confira se o app Kindle está instalado no celular. No iPhone ou Android, abra Mais/Outros no menu de compartilhamento e habilite Kindle. Se o navegador não permitir compartilhar arquivos diretamente, a Biblioteca baixa o EPUB como alternativa para você abri-lo no Kindle."},
  {q:"Quem consegue ver o livro que eu enviei?",a:"O livro aparece na sua Minha Biblioteca e entra como Pendente para o administrador. O administrador pode marcar Privado, deixando-o visível somente para você, ou Aprovar, fazendo o PDF entrar no catálogo geral."},
  {q:"O que significa Aprovado?",a:"Quando um PDF é aprovado, ele sai da fila Envios dos usuários, entra na aba Aprovados do painel administrativo e passa a aparecer no Acervo da Biblioteca. O administrador também pode removê-lo do catálogo ou excluí-lo."},
  {q:"Onde ficam armazenados os arquivos?",a:"PDFs, capas e versões EPUB para Kindle ficam armazenados no Google Drive conectado à Biblioteca Virtual. Os arquivos pessoais ficam organizados por usuário e o site controla quem pode acessá-los."},
  {q:"Por que autor, idioma e sinopse são pedidos?",a:"Esses dados organizam corretamente o catálogo e a versão Kindle. Ao escolher uma edição na pesquisa, a Biblioteca tenta preencher automaticamente título, autor, idioma, ano, páginas, categoria, sinopse e capa. Autor e sinopse são obrigatórios."},
  {q:"Meu upload falhou. O que devo verificar?",a:"Confirme se o arquivo é PDF, se possui até 200 MB e se sua conexão está estável. Não feche a página durante o envio. Se apenas a geração do EPUB falhar, seu PDF continua salvo e você poderá tentar novamente pelo botão Enviar ao Kindle."}
];

export default function HelpPage(){return <AppShell><main className="container help-page"><div className="page-head"><div><span className="eyebrow">CENTRAL DE AJUDA</span><h1>Precisa de ajuda?</h1><p>Respostas rápidas sobre leitura, privacidade, catálogo e Kindle.</p></div></div><section className="help-intro card panel"><div className="help-badge">?</div><div><h2>Como podemos ajudar?</h2><p className="muted">Toque em uma pergunta para abrir a resposta.</p></div></section><section className="faq-list">{faqs.map((item,index)=><details className="card faq-item" key={item.q} open={index===0}><summary>{item.q}<span>+</span></summary><div className="faq-answer">{item.a}</div></details>)}</section></main></AppShell>;}
